<?php

use Illuminate\Database\Seeder;
use App\Models\City;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            [ 1, 'اهر','Ahar','Ahar'],
            [ 1, 'عجبشير','Ajabshir','Ajabshir'],
            [ 1, 'آذر شهر','Azarshahr','Azarshahr'],
            [ 1, 'بناب','bonab','bonab'],
            [ 1, 'بستان آباد','Bostanabad','Bostanabad'],
            [ 1, 'چاراویماق','Charuymaq','Charuymaq'],
            [ 1, 'هشترود','Hashtrud','Hashtrud'],
            [ 1, 'هريس','Heris','Heris'],
            [ 1, 'جلفا','Jolfa','jolfa'],
            [ 1, 'كليبر','Kaleybar','Kaleybar'],
            [ 1, 'خداآفرین','Khoda Afarin','Khoda_Afarin'],
            [ 1, 'ملكان','Malekan','Malekan'],
            [ 1, 'مراغه','Maragheh','Maragheh'],
            [ 1, 'ميانه','Meyaneh','Meyaneh'],
            [ 1, 'مرند','Marand','marand'],
            [ 1, 'اسكو','Osku','Osku'],
            [ 1, 'سراب','Sarab','Sarab'],
            [ 1, 'شبستر','Shabestar','shabestar'],
            [ 1, 'تبريز','Tabriz','Tabriz'],
            [ 1, 'ورزقان','Varzaqan','Varzaqan'],
            [ 2, 'اروميه','Urmia','Urmia'],
            [ 2, 'نقده','Naqadeh','Naqadeh'],
            [ 2, 'ماكو','Maku','Maku'],
            [ 2, 'تكاب','Takab','Takab'],
            [ 2, 'خوي','Khoy','Khoy'],
            [ 2, 'مهاباد','Mahabad','Mahabad'],
            [ 2, 'سر دشت','Sardasht','Sardasht'],
            [ 2, 'چالدران','Chaldoran','Chaldoran'],
            [ 2, 'بوكان','Bukan','Bukan'],
            [ 2, 'مياندوآب','Miandoab','Miandoab'],
            [ 2, 'سلماس','Salmas','Salmas'],
            [ 2, 'شاهين دژ','Shahin Dezh','Shahin_Dezh'],
            [ 2, 'پيرانشهر','Piranshahr','Piranshahr'],
            [ 2, 'اشنويه','Oshnavieh','Oshnavieh'],
            [ 2, 'چایپاره','Chaypareh ','Chaypareh '],
            [ 2, 'پلدشت','Poldasht','Poldasht'],
            [ 2, 'شوط','Showt','Showt'],
            [ 3, 'اردبيل','Ardabil','Ardabil'],
            [ 3, 'سرعين','Sareyn','Sareyn'],
            [ 3, 'بيله سوار','Bileh Savar','Bileh_Savar'],
            [ 3, 'پارس آباد','Parsabad','Parsabad'],
            [ 3, 'خلخال','Khalkhal','Khalkhal'],
            [ 3, 'مشگين شهر','Meshgin Shahr','Meshgin_Shahr'],
            [ 3, 'نمين','Namin','Namin'],
            [ 3, 'نير','Nir','Nir'],
            [ 3, 'كوثر','Kowsar','Kowsar'],
            [ 3, 'گرمي','Germi','Germi'],
            [ 4, 'بوئین و میاندشت','Buin va Miandasht','Buin_va_Miandasht'],
            [ 4, 'مباركه','Mobarakeh','Mobarakeh'],
            [ 4, 'اردستان','Ardestan','Ardestan'],
            [ 4, 'خور و بیابانک','Khur and Biabanak','Khur_and_Biabanak'],
            [ 4, 'فلاورجان','Falavarjan','Falavarjan'],
            [ 4, 'فريدون شهر','Fereydunshahr','Fereydunshahr'],
            [ 4, 'كاشان','Kashan','Kashan'],
            [ 4, 'لنجان','Lenjan','Lenjan'],
            [ 4, 'گلپايگان','Golpayegan','Golpayegan'],
            [ 4, 'فريدن','Faridan','Faridan'],
            [ 4, 'نايين','Nain','Nain'],
            [ 4, 'اصفهان','Isfahan','Isfahan'],
            [ 4, 'نجف آباد','Najafabad','Najafabad'],
            [ 4, 'آران و بيدگل','Aran o Bidgol','Aran_o_Bidgol'],
            [ 4, 'چادگان','Chadegan','Chadegan'],
            [ 4, 'تیران و کرون','Tiran and Karvan','Tiran_and_Karvan'],
            [ 4, 'شهرضا','Shahreza','Shahreza'],
            [ 4, 'سميرم','Semirom','Semirom'],
            [ 4, 'خميني شهر','Khomeyni Shahr','Khomeyni Shahr'],
            [ 4, 'دهاقان','Dehaqan','Dehaqan'],
            [ 4, 'نطنز','Natanz','Natanz'],
            [ 4, 'برخوار','borkhar','borkhar'],
            [ 4, 'شاهین شهر و میمه','Shahin Shahr and Meymeh','Shahin_Shahr_and_Meymeh'],
            [ 4, 'خوانسار','Khvansar','Khvansar'],
            [ 6, 'ايلام','Ilam','Ilam'],
            [ 6, 'مهران','Mehran','Mehran'],
            [ 6, 'دهلران','Dehloran','Dehloran'],
            [ 6, 'آبدانان','Abdanan','Abdanan'],
            [ 6, 'چرداول','Chardaval','Chardaval'],
            [ 6, 'دره شهر','Darreh Shahr ','Darreh_Shahr '],
            [ 6, 'ايوان','Eyvan','Eyvan'],
            [ 6, 'بدره','Badreh','Badreh'],
            [ 6, 'سیروان','Sirvan','Sirvan'],
            [ 6, 'ملکشاهی','Malekshahi','Malekshahi'],
            [ 7, 'عسلویه','Asaluyeh','Asaluyeh'],
            [ 7, 'گناوه','Ganaveh','Ganaveh'],
            [ 7, 'دشتي','Dashti','Dashti'],
            [ 7, 'دشتستان','Dashtestan','Dashtestan'],
            [ 7, 'دير','Deyr','Deyr'],
            [ 7, 'بوشهر','Bushehr','Bushehr'],
            [ 7, 'كنگان','Kangan','Kangan'],
            [ 7, 'تنگستان','Tangestan','Tangestan'],
            [ 7, 'ديلم','Deylam','Deylam'],
            [ 7, 'جم','Jam','Jam'],
            [ 8, 'قرچك','Qarchak','Qarchak'],
            [ 8, 'پردیس','Pardis','Pardis'],
            [ 8, 'بهارستان','Baharestan','Baharestan'],
            [ 8, 'شمیرانات','Shemiran','Shemiran'],
            [ 8, 'رباط كريم','Robat Karim','Robat_Karim'],
            [ 8, 'فيروزكوه','ّFiruzkuh','ّFiruzkuh'],
            [ 8, 'تهران','Tehran','Tehran'],
            [ 8, 'ورامين','Varamin','Varamin'],
            [ 8, 'اسلامشهر','Eslamshahr ','Eslamshahr '],
            [ 8, 'ري','Ray','Ray'],
            [ 8, 'پاكدشت','Pakdasht','Pakdasht'],
            [ 8, 'پیشوا','Pishva','Pishva'],
            [ 8, 'قدس','Qods','Qods'],
            [ 8, 'ملارد','Malard','Malard'],
            [ 8, 'شهريار','Shahriar','Shahriar'],
            [ 8, 'دماوند','Damavand','Damavand'],
            [ 9, 'بن','Bon','Bon'],
            [ 9, 'سامان','Saman','Saman'],
            [ 9, 'کیار','Kiar','Kiar'],
            [ 9, 'بروجن','Borujen','Borujen'],
            [ 9, 'اردل','Ardal','Ardal'],
            [ 9, 'شهركرد','Shahrekord','Shahrekord'],
            [ 9, 'فارسان','Farsan','Farsan'],
            [ 9, 'کوهرنگ','Kuhrang','Kuhrang'],
            [ 9, 'لردگان','Lordegan','Lordegan'],
            [ 11, 'داورزن','Davarzan','Davarzan'],
            [ 11, 'كلات','Kalat','Kalat'],
            [ 11, 'بردسكن','Bardaskan','Bardaskan'],
            [ 11, 'مشهد','Mashhad','Mashhad'],
            [ 11, 'نيشابور','Nishapur','Nishapur'],
            [ 11, 'سبزوار','Sabzevar','Sabzevar'],
            [ 11, 'كاشمر','Kashmar','Kashmar'],
            [ 11, 'گناباد','Gonabad','Gonabad'],
            [ 11, 'تربت حيدريه','Torbat Heydarieh','Torbat_Heydarieh'],
            [ 11, 'خواف','Khvaf','Khvaf'],
            [ 11, 'تربت جام','Torbat Jam ','Torbat_Jam '],
            [ 11, 'تايباد','Taybad','Taybad'],
            [ 11, 'مه ولات','Mahvelat','Mahvelat'],
            [ 11, 'چناران','Chenaran','Chenaran'],
            [ 11, 'درگز','Dargaz','Dargaz'],
            [ 11, 'فیروزه','Firuzeh','Firuzeh'],
            [ 11, 'قوچان','Quchan','Quchan'],
            [ 11, 'سرخس','Sarakhs','Sarakhs'],
            [ 11, 'رشتخوار','Rashtkhvar','Rashtkhvar'],
            [ 11, 'بینالود','Binaloud','Binaloud'],
            [ 11, 'زاوه','Zaveh','Zaveh'],
            [ 11, 'جوین','Jowayin','Jowayin'],
            [ 11, 'بجستان','Bajestan','Bajestan'],
            [ 11, 'باخزر','Bakharz','Bakharz'],
            [ 11, 'فريمان','Fariman','Fariman'],
            [ 11, 'خلیل آباد','Khalilabad','Khalilabad'],
            [ 11, 'جغتای','Joghatai','Joghatai'],
            [ 11, 'خوشاب','Khoshab','Khoshab'],
            [ 10, 'زیرکوه','Zirkuh','Zirkuh'],
            [ 10, 'خوسف','Khusf','Khusf'],
            [ 10, 'درمیان','Darmian','Darmian'],
            [ 10, 'قائنات','Qaen','Qaen'],
            [ 10, 'بشرویه','Boshruyeh','Boshruyeh'],
            [ 10, 'فردوس','Ferdows','Ferdows'],
            [ 10, 'بيرجند','Birjand','Birjand'],
            [ 10, 'نهبندان','Nehbandan','Nehbandan'],
            [ 10, 'سربيشه','Sarbisheh','Sarbisheh'],
            [ 10, 'سرایان','Sarayan','Sarayan'],
            [ 11, 'طبس','Tabas','Tabas'],
            [ 12, 'بجنورد','Bojnord','Bojnord'],
            [ 12, 'راز و جرگلان','Raz and Jargalan','Raz_and_Jargalan'],
            [ 12, 'اسفراين','Esfarayen','Esfarayen'],
            [ 12, 'جاجرم','Jajrom ','Jajrom '],
            [ 12, 'شيروان','Shirvan','Shirvan'],
            [ 12, 'مانه و سملقان','Maneh and Samalqan ','Maneh_and_Samalqan '],
            [ 12, 'گرمه','Garmeh','Garmeh'],
            [ 12, 'فاروج','Faruj','Faruj'],
            [ 13, 'کارون','Karun','Karun'],
            [ 13, 'حمیدیه','Hamidiyeh','Hamidiyeh'],
            [ 13, 'آغاجری','Aghajari','Aghajari'],
            [ 13, 'شوشتر','Shushtar','Shushtar'],
            [ 13, 'دشت آزادگان','Dasht-e Azadegan','Dasht-e_Azadegan'],
            [ 13, 'اميديه','Omidiyeh','Omidiyeh'],
            [ 13, 'گتوند','Gotvand','Gotvand'],
            [ 13, 'شادگان','Shadegan','Shadegan'],
            [ 13, 'دزفول','Dezful','Dezful'],
            [ 13, 'رامشیر','Ramshir','Ramshir'],
            [ 13, 'بهبهان','Behbahan','Behbahan'],
            [ 13, 'باوی','Bavi','Bavi'],
            [ 13, 'انديمشك','Andimeshk','Andimeshk'],
            [ 13, 'اهواز','Ahvaz','Ahvaz'],
            [ 13, 'اندیکا','Andika','Andika'],
            [ 13, 'شوش','Shush','Shush'],
            [ 13, 'آبادان','Abadan','Abadan'],
            [ 13, 'هنديجان','Hendijan','Hendijan'],
            [ 13, 'خرمشهر','Khorramshahr','Khorramshahr'],
            [ 13, 'مسجد سليمان','Masjed Soleyman','Masjed_Soleyman'],
            [ 13, 'ايذه','Izeh','Izeh'],
            [ 13, 'رامهرمز','Ramhormoz','Ramhormoz'],
            [ 13, 'باغ ملك','Bagh Malek','Bagh_Malek'],
            [ 13, 'هفتکل','Haftkel','Haftkel'],
            [ 13, 'هويزه','Hoveyzeh','Hoveyzeh'],
            [ 13, 'ماهشهر','Mahshahr','Mahshahr'],
            [ 13, 'لالي','Lali','Lali'],
            [ 14, 'زنجان','Zanjan','Zanjan'],
            [ 14, 'ابهر','Abhar','Abhar'],
            [ 14, 'خدابنده','Khodabandeh','Khodabandeh'],
            [ 14, 'ماهنشان','Mahneshan','Mahneshan'],
            [ 14, 'خرمدره','Khorramdarreh','Khorramdarreh'],
            [ 14, 'ايجرود','Ijrud','Ijrud'],
            [ 14, 'طارم','Tarom','Tarom'],
            [ 14, 'سلطانیه','Soltaniyeh','Soltaniyeh'],
            [ 15, 'سمنان','Semnan','Semnan'],
            [ 15, 'شاهرود','Shahrud','Shahrud'],
            [ 15, 'گرمسار','Garmsar','Garmsar'],
            [ 15, 'سرخه','Sorkheh','Sorkheh'],
            [ 15, 'دامغان','Damghan','Damghan'],
            [ 15, 'آرادان','Aradan','Aradan'],
            [ 15, 'مهدی شهر','Mehdishahr','Mehdishahr'],
            [ 15, 'میامی','Meyami','Meyami'],
            [ 16, 'زاهدان','Zahedan','Zahedan'],
            [ 16, 'بمپور','Bampur','Bampur'],
            [ 16, 'چابهار','Chabahar','Chabahar'],
            [ 16, 'خاش','Khash','Khash'],
            [ 16, 'سراوان','Saravan','Saravan'],
            [ 16, 'زابل','Zabol','Zabol'],
            [ 16, 'سرباز','Sarbaz','Sarbaz'],
            [ 16, 'قصر قند','Qasr-e Qand','Qasr-e_Qand'],
            [ 16, 'نيكشهر','Nik Shahr','Nik_Shahr'],
            [ 16, 'کنارک','Konarak','Konarak'],
            [ 16, 'ايرانشهر','Iranshahr','Iranshahr'],
            [ 16, 'زهک','Zehak','Zehak'],
            [ 16, 'سیب و سوران','Sib and Suran','Sib_and_Suran'],
            [ 16, 'ميرجاوه','Mirjaveh','Mirjaveh'],
            [ 16, 'دلگان','Dalgan','Dalgan'],
            [ 16, 'هیرمند','Hirmand','Hirmand'],
            [ 16, 'مهرستان','Mehrestan','Mehrestan'],
            [ 16, 'فنوج','Fanuj','Fanuj'],
            [ 16, 'هامون','Hamoun','Hamoun'],
            [ 16, 'نیمروز','Nimrouz','Nimrouz'],
            [ 17, 'شيراز','Shiraz','Shiraz'],
            [ 17, 'اقليد','Eqlid','Eqlid'],
            [ 17, 'داراب','Darab','Darab'],
            [ 17, 'فسا','Fasa','Fasa'],
            [ 17, 'مرودشت','Marvdasht','Marvdasht'],
            [ 17, 'خرم بيد','Khorrambid','Khorrambid'],
            [ 17, 'آباده','Abadeh','Abadeh'],
            [ 17, 'كازرون','Kazerun','Kazerun'],
            [ 17, 'گراش','Gerash','Gerash'],
            [ 17, 'ممسني','Mamasani','Mamasani'],
            [ 17, 'سپيدان','Sepidan','Sepidan'],
            [ 17, 'لارستان','Larestan','Larestan'],
            [ 17, 'فيروز آباد','Firuzabad','Firuzabad'],
            [ 17, 'جهرم','Jahrom','Jahrom'],
            [ 17, 'ني ريز','Neyriz','Neyriz'],
            [ 17, 'استهبان','Estahban','Estahban'],
            [ 17, 'لامرد','Lamerd','Lamerd'],
            [ 17, 'مهر','Mohr','Mohr'],
            [ 17, 'پاسارگاد','Pasargad','Pasargad'],
            [ 17, 'ارسنجان','Arsanjan','Arsanjan'],
            [ 17, 'قيروكارزين','Qir and Karzin','Qir_and_Karzin'],
            [ 17, 'رستم','Rostam','Rostam'],
            [ 17, 'فراشبند','Farashband','Farashband'],
            [ 17, 'سروستان','Sarvestan','Sarvestan'],
            [ 17, 'زرین دشت','Zarrin Dasht','Zarrin_Dasht'],
            [ 17, 'کوار','Kavar','Kavar'],
            [ 17, 'بوانات','Bavanat','Bavanat'],
            [ 17, 'خرامه','Kharameh','Kharameh'],
            [ 17, 'خنج','Khonj','Khonj'],
            [ 18, 'قزوين','Qazvin','Qazvin'],
            [ 18, 'تاكستان','Takestan','Takestan'],
            [ 18, 'آبيك','Abyek','Abyek'],
            [ 18, 'بوئين زهرا','Buin Zahra','Buin_Zahra'],
            [ 18, 'البرز','Alborz','Alborz'],
            [ 18, 'آوج','Avaj','Avaj'],
            [ 19, 'قم','Qom','Qom'],
            [ 5, 'طالقان','Taleqan','Taleqan'],
            [ 5, 'اشتهارد','Eshtehard','Eshtehard'],
            [ 5, 'كرج','Karaj','Karaj'],
            [ 5, 'نظر آباد','Nazarabad','Nazarabad'],
            [ 5, 'ساوجبلاغ‎','Savojbolagh','Savojbolagh']  ,
            [ 5, 'فردیس','Fardis','Fardis'],
            [ 20, 'سنندج','Sanandaj','Sanandaj'],
            [ 20, 'ديواندره','Divandarreh','Divandarreh'],
            [ 20, 'بانه','Baneh','Baneh'],
            [ 20, 'بيجار','Bijar','Bijar'],
            [ 20, 'سقز','Saqqez','Saqqez'],
            [ 20, 'كامياران','Kamyaran','Kamyaran'],
            [ 20, 'قروه','Qorveh','Qorveh'],
            [ 20, 'مريوان','Marivan','Marivan'],
            [ 20, 'سروآباد‎','Sarvabad','Sarvabad'],
            [ 20, 'دهگلان‎','Dehgolan','Dehgolan'],
            [ 21, 'كرمان','Kerman','Kerman'],
            [ 21, 'راور','Ravar','Ravar'],
            [ 21, 'شهر بابک','Shahr-e Babak','Shahr-e_Babak'],
            [ 21, 'انار','Anar','Anar'],
            [ 21, 'کوهبنان','Kuhbanan','Kuhbanan'],
            [ 21, 'رفسنجان','Rafsanjan','Rafsanjan'],
            [ 21, 'سيرجان','Sirjan','Sirjan'],
            [ 21, 'كهنوج','Kahnuj','Kahnuj'],
            [ 21, 'زرند','Zarand','Zarand'],
            [ 21, 'ریگان','Rigan','Rigan'],
            [ 21, 'بم','Bam','Bam'],
            [ 21, 'جيرفت','Jiroft','Jiroft'],
            [ 21, 'عنبرآباد','Anbarabad','Anbarabad'],
            [ 21, 'بافت','Baft','Baft'],
            [ 21, 'ارزوئيه','Arzuiyeh','Arzuiyeh'],
            [ 21, 'بردسیر','Bardsir','Bardsir'],
            [ 21, 'فهرج','Fahraj','Fahraj'],
            [ 21, 'فاریاب','Faryab','Faryab'],
            [ 21, 'منوجان','Manujan','Manujan'],
            [ 21, 'نرماشیر','Narmashir','Narmashir'],
            [ 21, 'قلعه گنج','Qaleh Ganj','Qaleh_Ganj'],
            [ 21, 'رابر','Rabor','Rabor'],
            [ 21, 'رودبار جنوب','Rudbar-e Jonubi','Rudbar-e_Jonubi'],
            [ 22, 'كرمانشاه','Kermanshah','Kermanshah'],
            [ 22, 'اسلام آباد غرب','Eslamabad-e Gharb','Eslamabad-e_Gharb'],
            [ 22, 'سر پل ذهاب','Sarpol-e Zahab','Sarpol-e_Zahab'],
            [ 22, 'كنگاور','Kangavar','Kangavar'],
            [ 22, 'سنقر','Sonqor','Sonqor'],
            [ 22, 'قصر شيرين','Qasr-e Shirin','Qasr-e_Shirin'],
            [ 22, 'گيلان غرب','Gilan-e Gharb','Gilan-e_Gharb'],
            [ 22, 'هرسين','Harsin','Harsin'],
            [ 22, 'صحنه','Sahneh','Sahneh'],
            [ 22, 'پاوه','Paveh','Paveh'],
            [ 22, 'جوانرود','Javanrud','Javanrud'],
            [ 22, 'دالاهو','Dalahu','Dalahu'],
            [ 22, 'روانسر','Ravansar','Ravansar'],
            [ 22, 'ثلاث باباجانی','Salas-e Babajani','Salas-e_Babajani'],
            [ 23, 'ياسوج','Yasuj','Yasuj'],
            [ 23, 'گچساران','Gachsaran','Gachsaran'],
            [ 23, 'دنا','Dana','Dana'],
            [ 23, 'کهگیلویه‎','Kohgiluyeh','Kohgiluyeh'],
            [ 23, 'لنده','Landeh','Landeh'],
            [ 23, 'بهمئی','Bahmai','Bahmai'],
            [ 23, 'باشت','Basht','Basht'],
            [ 23, 'بویراحمد','Boyer Ahmad','Boyer_Ahmad'],
            [ 23, 'چرام','Charam','Charam'],
            [ 24, 'گرگان','Gorgan','Gorgan'],
            [ 24, 'آق قلا','Aqqala','Aqqala'],
            [ 24, 'گنبد كاووس','Gonbad-e Qabus','Gonbad-e_Qabus'],
            [ 24, 'علی آباد','Aliabad','Aliabad'],
            [ 24, 'مينو دشت','Minudasht','Minudasht'],
            [ 24, 'تركمن','Torkaman','Torkaman'],
            [ 24, 'كردكوي','Kordkuy','Kordkuy'],
            [ 24, 'بندر گز','Bandar-e Gaz','Bandar-e_Gaz'],
            [ 24, 'كلاله','Kalaleh','Kalaleh'],
            [ 24, 'آزاد شهر','Azadshahr','Azadshahr'],
            [ 24, 'راميان','Ramian','Ramian'],
            [ 24, 'گالیکش‎','Galikash','Galikash'],
            [ 24, 'مراوه تپه','Maraveh Tappeh','Maraveh_Tappeh'],
            [ 24, 'گمیشان','Gomishan','Gomishan'],
            [ 25, 'رشت','Rasht','Rasht'],
            [ 25, 'لنگرود','Langarud','Langarud'],
            [ 25, 'رودسر','Rudsar','Rudsar'],
            [ 25, 'طوالش','Talesh','Talesh'],
            [ 25, 'آستارا','Astara','Astara'],
            [ 25, 'آستانه اشرفيه','Astaneh-ye Ashrafiyeh','Astaneh-ye_Ashrafiyeh'],
            [ 25, 'رودبار','Rudbar','Rudbar'],
            [ 25, 'فومن','Fuman','Fuman'],
            [ 25, 'صومعه سرا','Sowme-eh Sara','Sowme-eh_Sara'],
            [ 25, 'بندرانزلي','Bandar-e Anzali','Bandar-e_Anzali'],
            [ 25, 'رضوانشهر','Rezvanshahr','Rezvanshahr'],
            [ 25, 'ماسال','Masal','Masal'],
            [ 25, 'شفت','Shaft','Shaft'],
            [ 25, 'سياهكل','Siahkal','Siahkal'],
            [ 25, 'املش','Amlash','Amlash'],
            [ 25, 'لاهیجان','Lahijan','Lahijan'],
            [ 26, 'خرم آباد','Khorramabad','Khorramabad'],
            [ 26, 'دلفان','Delfan','Delfan'],
            [ 26, 'بروجرد','Borujerd','Borujerd'],
            [ 26, 'دورود','Dorud','Dorud'],
            [ 26, 'اليگودرز','Aligudarz','Aligudarz'],
            [ 26, 'ازنا','Azna','Azna'],
            [ 26, 'كوهدشت','Kuhdasht','Kuhdasht'],
            [ 26, 'سلسله','Selseleh','Selseleh'],
            [ 26, 'پلدختر','Pol-e Dokhtar','Pol-e_Dokhtar'],
            [ 26, 'دوره','Dowreh','Dowreh'],
            [ 26, 'رومشکان','Rumeshkhan','Rumeshkhan'],
            [ 27, 'ساري','Sari','Sari'],
            [ 27, 'آمل','Amol','Amol'],
            [ 27, 'بابل','Babol','Babol'],
            [ 27, 'بابلسر','Babolsar','Babolsar'],
            [ 27, 'بهشهر','Behshahr','Behshahr'],
            [ 27, 'تنكابن','Tonekabon','Tonekabon'],
            [ 27, 'جويبار','Juybar','Juybar'],
            [ 27, 'چالوس','Chalus','Chalus'],
            [ 27, 'رامسر','Ramsar','Ramsar'],
            [ 27, 'سواد كوه','Savadkuh','Savadkuh'],
            [ 27, 'قائم شهر','Qaem Shahr','Qaem_Shahr'],
            [ 27, 'نكا','Neka','Neka'],
            [ 27, 'نور','Nur','Nur'],
            [ 27, 'نوشهر','Nowshahr','Nowshahr'],
            [ 27, 'محمودآباد','Mahmudabad','Mahmudabad'],
            [ 27, 'فریدونکنار','Fereydunkenar','Fereydunke  nar'],
            [ 27, 'عباس آباد','Abbasabad','Abbasabad'],
            [ 27, 'گلوگاه','Galugah','Galugah'],
            [ 27, 'میاندورود','Miandorud','Miandorud'],
            [ 27, 'سیمرغ','Simorgh','Simorgh'],
            [ 27, 'کلاردشت','Kelardasht','Kelardasht'],
            [ 27, 'سوادکوه شمالی','Savadkooh Shomali','Savadkooh_Shomali'],
            [ 28, 'اراك','Arak','Arak'],
            [ 28, 'آشتيان','Ashtian','Ashtian'],
            [ 28, 'تفرش','Tafresh','Tafresh'],
            [ 28, 'خمين','Khomeyn','Khomeyn'],
            [ 28, 'دليجان','Delijan','Delijan'],
            [ 28, 'ساوه','Saveh','Saveh'],
            [ 28, 'زرندیه','Zarandieh','Zarandieh'],
            [ 28, 'محلات','Mahallat','Mahallat'],
            [ 28, 'شازند','Shazand','Shazand'],
            [ 28, 'فراهان','Farahan','Farahan'],
            [ 28, 'خنداب','Khondab','Khondab'],
            [ 28, 'کمیجان','Komijan','Komijan'],
            [ 29, 'بندرعباس','Bandar Abbas','Bandar_Abbas'],
            [ 29, 'قشم','Qeshm','Qeshm'],
            [ 29, 'بندر لنگه','Bandar Lengeh','Bandar_Lengeh'],
            [ 29, 'بستك','Bastak','Bastak'],
            [ 29, 'حاجی آباد هرمزگان','Hajjiabad Hormozgan','Hajjiabad_Hormozgan'],
            [ 29, 'رودان','Rudan','Rudan'],
            [ 29, 'ميناب','Minab','Minab'],
            [ 29, 'ابوموسي','Abumusa','Abumusa'],
            [ 29, 'جاسک','Jask','Jask'],
            [ 29, 'خمیر','Khamir','Khamir'],
            [ 29, 'پارسیان','Parsian','Parsian'],
            [ 29, 'بشاگرد','Bashagard','Bashagard'],
            [ 29, 'سیریک','Sirik','Sirik'],
            [ 29, 'حاجی آباد','Hajjiabad','Hajjiabad'],
            [ 30, 'همدان','Hamadan','Hamadan'],
            [ 30, 'ملاير','Malayer','Malayer'],
            [ 30, 'تويسركان','Tuyserkan','Tuyserkan'],
            [ 30, 'نهاوند','Nahavand','Nahavand'],
            [ 30, 'كبودر اهنگ','Kabudarahang','Kabudarahang'],
            [ 30, 'رزن','Razan','Razan'],
            [ 30, 'اسدآباد','Asadabad','Asadabad'],
            [ 30, 'بهار','Bahar','Bahar'],
            [ 30, 'فامنین','Famenin','Famenin'],
            [ 31, 'يزد','Yazd','Yazd'],
            [ 31, 'تفت','Taft','Taft'],
            [ 31, 'اردكان','Ardakan','Ardakan'],
            [ 31, 'ابركوه','Abarkuh','Abarkuh'],
            [ 31, 'ميبد','Meybod','Meybod'],
            [ 31, 'بافق','Bafq','Bafq'],
            [ 31, 'صدوق','Saduq','Saduq'],
            [ 31, 'مهریز','Mehriz','Mehriz'],
            [ 31, 'خاتم','Khatam','Khatam'],
            [ 31, 'بهاباد','Behabad','Behabad']
        ];

        foreach ($cities as $city) {
            City::create([
                'province_id' => $city[0],
                'city_name_fa' => $city[1],
                'city_name_en' => $city[2]
            ]);
        }
    }
}